/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 19:42:43 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution1962;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Solution1962_ESTest extends Solution1962_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution1962 solution1962_0 = new Solution1962();
      int[] intArray0 = new int[3];
      intArray0[2] = 3973;
      int int0 = solution1962_0.minStoneSum(intArray0, 1277);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution1962 solution1962_0 = new Solution1962();
      int[] intArray0 = new int[7];
      int int0 = solution1962_0.minStoneSum(intArray0, (-701));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution1962 solution1962_0 = new Solution1962();
      int[] intArray0 = new int[9];
      intArray0[0] = (-435);
      int int0 = solution1962_0.minStoneSum(intArray0, 0);
      assertEquals((-435), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[1];
      Solution1962 solution1962_0 = new Solution1962();
      solution1962_0.minStoneSum(intArray0, 5422);
      // Undeclared exception!
      solution1962_0.minStoneSum(intArray0, 5422);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution1962 solution1962_0 = new Solution1962();
      // Undeclared exception!
      try { 
        solution1962_0.minStoneSum((int[]) null, 1838);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
