/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 18:31:10 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution1449;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Solution1449_ESTest extends Solution1449_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[9];
      // Undeclared exception!
      solution1449_0.largestNumber(intArray0, 2172);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      // Undeclared exception!
      try { 
        solution1449_0.largestNumber((int[]) null, 1695);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution1449", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution1449_0.largestNumber(intArray0, (-2009));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -2008
         //
         verifyException("original.Solution1449", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[6];
      // Undeclared exception!
      try { 
        solution1449_0.largestNumber(intArray0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("original.Solution1449", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[9];
      String string0 = solution1449_0.largestNumber(intArray0, 6);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[13];
      intArray0[0] = 295;
      String string0 = solution1449_0.largestNumber(intArray0, 295);
      assertEquals("1", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution1449 solution1449_0 = new Solution1449();
      int[] intArray0 = new int[18];
      String string0 = solution1449_0.largestNumber(intArray0, 0);
      assertEquals("", string0);
  }
}
