/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 19:23:13 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2141;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Solution2141_ESTest extends Solution2141_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      int[] intArray0 = new int[6];
      intArray0[0] = 1021;
      intArray0[1] = 1021;
      long long0 = solution2141_0.maxRunTime((-15), intArray0);
      assertEquals(2042L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      int[] intArray0 = new int[6];
      intArray0[0] = 1021;
      long long0 = solution2141_0.maxRunTime((-15), intArray0);
      assertEquals(1021L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      int[] intArray0 = new int[6];
      intArray0[0] = 1021;
      intArray0[1] = 1021;
      long long0 = solution2141_0.maxRunTime(1021, intArray0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      int[] intArray0 = new int[6];
      intArray0[0] = (-1);
      long long0 = solution2141_0.maxRunTime((-1), intArray0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      // Undeclared exception!
      try { 
        solution2141_0.maxRunTime((-597), (int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2141", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution2141 solution2141_0 = new Solution2141();
      int[] intArray0 = new int[1];
      intArray0[0] = 1;
      long long0 = solution2141_0.maxRunTime(1, intArray0);
      assertEquals(1L, long0);
  }
}
