/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:05:06 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2907;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2907_ESTest extends Solution2907_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[6];
      intArray0[0] = (-1);
      intArray0[3] = 2723;
      int[] intArray1 = new int[9];
      intArray1[0] = 2723;
      intArray1[3] = 2287;
      int int0 = solution2907_0.maxProfit(intArray0, intArray1);
      assertEquals(5010, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[4];
      intArray0[0] = (-2284);
      int[] intArray1 = new int[9];
      int int0 = solution2907_0.maxProfit(intArray0, intArray1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        solution2907_0.maxProfit((int[]) null, intArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2907", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2907 solution2907_0 = new Solution2907();
      int[] intArray0 = new int[6];
      intArray0[1] = (-804);
      int[] intArray1 = new int[3];
      // Undeclared exception!
      try { 
        solution2907_0.maxProfit(intArray0, intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("original.Solution2907", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int[] intArray0 = new int[4];
      intArray0[3] = 188;
      intArray0[1] = 1;
      intArray0[2] = 56;
      Solution2907 solution2907_0 = new Solution2907();
      int int0 = solution2907_0.maxProfit(intArray0, intArray0);
      assertEquals(245, int0);
  }
}
