/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:34:29 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2470;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2470_ESTest extends Solution2470_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2470 solution2470_0 = new Solution2470();
      int[] intArray0 = new int[2];
      intArray0[0] = (-1794);
      intArray0[1] = 359;
      solution2470_0.subarrayLCM(intArray0, 1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2470 solution2470_0 = new Solution2470();
      // Undeclared exception!
      try { 
        solution2470_0.subarrayLCM((int[]) null, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2470", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2470 solution2470_0 = new Solution2470();
      int[] intArray0 = new int[2];
      intArray0[0] = (-1794);
      intArray0[1] = 359;
      int int0 = solution2470_0.subarrayLCM(intArray0, 359);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2470 solution2470_0 = new Solution2470();
      int[] intArray0 = new int[2];
      intArray0[0] = (-1794);
      // Undeclared exception!
      try { 
        solution2470_0.subarrayLCM(intArray0, 359);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("original.Solution2470", e);
      }
  }
}
