/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 00:21:23 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution3287;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution3287_ESTest extends Solution3287_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[7];
      intArray0[0] = 2;
      intArray0[1] = 2;
      int int0 = solution3287_0.maxValue(intArray0, 2);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[2];
      intArray0[0] = 1;
      int int0 = solution3287_0.maxValue(intArray0, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[2];
      // Undeclared exception!
      solution3287_0.maxValue(intArray0, 1077);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      // Undeclared exception!
      try { 
        solution3287_0.maxValue((int[]) null, (-2961));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution3287", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution3287_0.maxValue(intArray0, (-2336));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -2334
         //
         verifyException("original.Solution3287", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[7];
      intArray0[4] = (-1);
      // Undeclared exception!
      try { 
        solution3287_0.maxValue(intArray0, 2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 128
         //
         verifyException("original.Solution3287", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution3287 solution3287_0 = new Solution3287();
      int[] intArray0 = new int[3];
      int int0 = solution3287_0.maxValue(intArray0, 0);
      assertEquals(0, int0);
  }
}
