/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 02:17:03 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution3082;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution3082_ESTest extends Solution3082_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      int[] intArray0 = new int[1];
      solution3082_0.sumOfPower(intArray0, 3730);
      solution3082_0.sumOfPower(intArray0, 3730);
      // Undeclared exception!
      solution3082_0.sumOfPower(intArray0, 3730);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      // Undeclared exception!
      try { 
        solution3082_0.sumOfPower((int[]) null, 1016);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution3082", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        solution3082_0.sumOfPower(intArray0, (-1391));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -1390
         //
         verifyException("original.Solution3082", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution3082_0.sumOfPower(intArray0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("original.Solution3082", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      int[] intArray0 = new int[1];
      intArray0[0] = 3730;
      int int0 = solution3082_0.sumOfPower(intArray0, 3730);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution3082 solution3082_0 = new Solution3082();
      int[] intArray0 = new int[3];
      int int0 = solution3082_0.sumOfPower(intArray0, 0);
      assertEquals(27, int0);
  }
}
